config/routes.rb
Rails.application.routes.draw do
  root 'gists#index'

  resources :gists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :gists
end

app/models/gist.rb
# == Schema Information
#
# Table name: gists
#
#  id          :bigint(8)        not null, primary key
#  filename    :string
#  description :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint(8)
#

class Gist < ApplicationRecord
  belongs_to :category

  validates :filename, presence: true, length: { minimum: 3, maximum: 55 }
  validates :content, presence: true
  validates :description, presence: true

  def self.search(search)
    where(
      'filename ILIKE ? OR description ILIKE ? OR content ILIKE ?',
      "%#{search}%",
      "%#{search}%",
      "%#{search}%"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :find_gist, only: %i(show edit update destroy)

  def index
    @categories = Category.all

    if params[:search]
      @gists = Gist.search(params[:search]).order('created_at DESC')
    elsif params[:category]
      @category = Category.find_by(name: params[:category])
      @gists = Gist.where(category_id: @category.id).order('created_at DESC')
    else
      @gists = Gist.all.order('created_at DESC')
    end
  end

  def new
    @categories = Category.all
    @gist = Gist.new
  end

  def create
    @gist = Gist.new(gist_params)

    if @gist.save
      flash[:notice] = 'New gist successfully added!'
      redirect_to gists_path
    else
      flash[:error] = 'Something wrong happened. Please try again!'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @gist.update(gist_params)
      flash[:notice] = 'New gist successfully added!'
      redirect_to @gist
    else
      flash[:error] = 'Something wrong happened. Please try again!'
      render :edit
    end
  end

  def destroy
    @gist.destroy
    redirect_to gists_path
  end

  private

  def find_gist
    @gist = Gist.find(params[:id])
  end

  def gist_params
    params.require(:gist).permit(:filename, :description, :content, :category_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gists/edit.html.erb
<h2>Edit gist</h2>

<%= form_for @gist, url: { action: 'update' }, html: { class: 'gist-form' } do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control', placeholder: 'Gist description...' %>
    </div>
    <div class="form-group">
      <%= f.label :filename %>
      <%= f.text_field :filename, class: 'form-control', placeholder: 'Filename including extension...' %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control gist-content', rows: 3 %>
    </div>
    <%= f.submit 'Create gist', class: 'btn btn-secondary float-right gist-submit' %>
  </fieldset>
<% end %>

app/views/gists/index.html.erb
<%= render 'shared/categories' %>

<% if params[:search] %>
  <h4 class="result-title font-weight-light">
    <%= @gists.length %> result<%= 's' if @gists.length > 1 %>
  </h4>
<% end %>

<% @gists.each do |gist| %>
  <section class="gist-home">
    <div class="gist-heading">
      <%= image_tag 'https://via.placeholder.com/30x30', alt: 'user avatar', class: 'gist-avatar' %>
      <a href="#"><p class="gist-username">stephanyan</p></a> /
      <%= link_to gist.filename, gist, class: 'gist-filename' %>
    </div>
    <% if gist.created_at == gist.updated_at %>
      <p class="gist-time-ago font-weight-light">Created <%= time_ago_in_words(gist.created_at) %> ago</p>
    <% else %>
      <p class="gist-time-ago font-weight-light">Updated <%= time_ago_in_words(gist.updated_at) %> ago</p>
    <% end %>
    <p class="gist-description font-weight-light"><%= gist.description %></p>
    <div class="gist-content">
      <p><%= gist.content %></p>
    </div>
  </section>
<% end %>

app/views/gists/new.html.erb
<h2>Create a new gist</h2>

<%= form_for @gist, url: { action: 'create' }, html: { class: 'gist-form' } do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control',
          placeholder: 'Gist description...', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :filename %>
      <%= f.text_field :filename, class: 'form-control',
          placeholder: 'Filename including extension...', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control gist-content',
          rows: 3, required: true %>
    </div>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name,
        { prompt: 'Select a language' }, class: 'form-control', required: true %>
    </div>
    <%= f.submit 'Create gist', class: 'btn btn-secondary float-right gist-submit' %>
  </fieldset>
<% end %>

app/views/gists/show.html.erb
<section class="gist-home">
  <div class="gist-heading">
    <%= image_tag 'https://via.placeholder.com/30x30', alt: 'user avatar', class: 'gist-avatar' %>
    <a href="#"><p class="gist-username">stephanyan</p></a> /
    <%= link_to @gist.filename, @gist, class: 'gist-filename' %>
  </div>
  <% if @gist.created_at == @gist.updated_at %>
    <p class="gist-time-ago font-weight-light">Created <%= time_ago_in_words(@gist.created_at) %> ago</p>
  <% else %>
    <p class="gist-time-ago font-weight-light">Updated <%= time_ago_in_words(@gist.updated_at) %> ago</p>
  <% end %>
  <p class="gist-description font-weight-light"><%= @gist.description %></p>
  <div class="gist-content">
    <p><%= @gist.content %></p>
  </div>
  <br>
  <div class="float-right">
    <%= link_to edit_gist_path(@gist), title: 'Click to edit' do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to gist_path(@gist), method: :delete,
        data: { confirm: "Are you sure?" }, title: 'Click to delete' do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GistappV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag 'favicon-32x32.png', rel: 'icon', sizes: '32x32', type: 'image/png' %>
    <%= favicon_link_tag 'favicon-16x16.png', rel: 'icon', sizes: '16x16', type: 'image/png' %>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.3.1/css/all.css',
        integrity: 'sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU',
        crossorigin: 'anonymous' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,700' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/flatly/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= flash[:notice] %></p>
  </div>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="container">
    <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= flash[:error] %></p>
  </div>
<% end %>

app/views/shared/_categories.html.erb
<ul class="nav nav-pills">
  <% if !params[:category] || params[:category] == 'all' %>
    <li class="nav-item">
      <%= link_to 'All', gists_path, class: 'nav-link active' %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to 'All', gists_path, class: 'nav-link' %>
    </li>
  <% end %>
  <% @categories.each do |category| %>
    <% if params[:category] == category.name %>
      <li class="nav-item">
        <%= link_to category.name, gists_path(category: category.name), class: 'nav-link active' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to category.name, gists_path(category: category.name), class: 'nav-link' %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
<footer>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js',
      integrity: 'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo',
      crossorigin: 'anonymous' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js',
      integrity: 'sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49',
      crossorigin: 'anonymous' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js',
      integrity: 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy',
      crossorigin: 'anonymous' %>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

  <div class="container">

    <a class="navbar-brand" href="#"><strong>GitHub</strong><span class="navbar-brand-gist">Gist</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">

      <%= form_tag(gists_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
        <%= text_field_tag(:search, params[:search], placeholder: 'Search...',
        class: 'form-control mr-sm-2 search-gist') %>
      <% end %>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'All gists', gists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">GitHub</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'New gist', new_gist_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag 'https://via.placeholder.com/20x20', alt: 'user avatar', class: 'navbar-avatar' %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Signed in as <br><strong>stephanyan</strong></a>
            <div class="dropdown-divider"></div>
            <%= link_to 'Your gists', gists_path, class: 'dropdown-item' %>
            <a class="dropdown-item" href="#">Sign out</a>
          </div>
        </li>
      </ul>

    </div>

  </div>

</nav>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>